{% set name = "nllgrid" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nllgrid-{{ version }}.tar.gz
  sha256: 853e0cb7c0fcf3970137de240018d9477ce7b446f6a0e22f1c864f206711a8d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python >=3.7
  run:
    - numpy >=1.0
    - scipy >=0.16
    - pyproj
    - python >=3.7

test:
  imports:
    - nllgrid
  commands:
    - pip check
  requires:
    - pip
    - pytest
  commands:
    - pytest --pyargs nllgrid

about:
  home: https://github.com/claudiodsf/nllgrid
  summary: Python class for reading and writing NonLinLoc grid files
  license: CECILL-2.1
  license_file: LICENSE.txt
  description: |
    Python class for reading and writing NonLinLoc grid files.
  dev_url: https://github.com/claudiodsf/nllgrid

extra:
  recipe-maintainers:
    - claudiodsf
